### ISSUE TITLE
Real Server-Push?

### ISSUE THREAD

**Issue by YoSev** [rzschech/gwt-comet#2]
Hey, 

this is less an issue then a question about the following README content:
The library implements Comet by streaming messages **over long lived HTTP requests** to minimise latency and bandwidth requirements and maximise the throughput. **This is opposed to many other implementations which use polling or long polling techniques.**

What is exactly the difference between "long lived HTTP requests" and "long polling"?

thanks

**Comment by rzschech** [comment]
https://en.wikipedia.org/wiki/Comet_(programming)#Implementations
